version: "3"
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./api:/app"
  testing:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./app:/app"
